## 用户
CREATE TABLE IF NOT EXISTS USER (
  LOGINNAME  VARCHAR(50)  NOT NULL PRIMARY KEY,
  PWD        VARCHAR(256) NOT NULL,
  NAME       VARCHAR(256) NOT NULL,
  BIRTH      DATE,
  SEX        INT,
  CREATEDATE DATE,
  ROLECODE   VARCHAR(20),
  STATE      VARCHAR(2),
  COMFLAG    VARCHAR(50)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8;
## 角色
CREATE TABLE IF NOT EXISTS ROLE (
  CODE VARCHAR(20)  NOT NULL PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8;
## 帐套
CREATE TABLE IF NOT EXISTS CURTAIN (
  ID         BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  COMFLAG    VARCHAR(20)  NOT NULL,
  CODE       VARCHAR(20)  NOT NULL,
  NAME       VARCHAR(256) NOT NULL,
  STARTMONTH DATE  NOT NULL,
  USERID VARCHAR(50),
  STATE VARCHAR(2)
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 帐套-用户
CREATE TABLE IF NOT EXISTS CURTAIN_USER (
  CURTAIN_ID BIGINT(20) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  KEY FK_CURTAIN_ID (CURTAIN_ID),
  KEY FK_USER_ID (USER_ID),
  CONSTRAINT FK_CURTAIN_ID FOREIGN KEY (CURTAIN_ID) REFERENCES CURTAIN(LOGINNAME),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
## 科目
CREATE TABLE IF NOT EXISTS SUBJECT (
  ID         BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CURTAINID  BIGINT(20)  NOT NULL,
  CODE       VARCHAR(10)  NOT NULL,
  NAME       VARCHAR(256) NOT NULL,
  BALANCE    VARCHAR(10)  NOT NULL
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 凭证
CREATE TABLE IF NOT EXISTS VOUCHER (
  ID          BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CURTAINID   BIGINT(20)  NOT NULL,
  CODE        BIGINT(20)  NOT NULL,
  CREATEDATE  DATE NOT NULL,
  BILLNUM     INT,
  JINAME      VARCHAR(20),
  SHENNAME    VARCHAR(20),
  CHUNAME     VARCHAR(20),
  ZHINAME     VARCHAR(20),
  DEBIT       BIGINT(20),
  CREDIT      BIGINT(20),
  DESCRIPTION VARCHAR(225),
  VOUCHERSTATUS VARCHAR(2),
  SYSCODE VARCHAR(20)
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 凭证明细
CREATE TABLE IF NOT EXISTS VOUCHERDETAIL (
  ID          BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  SUBJECT_ID  BIGINT(20) NOT NULL,
  VOUCHER_ID  BIGINT(20) NOT NULL,
  DEBIT       BIGINT(20),
  CREDIT      BIGINT(20),
  DESCRIPTION VARCHAR(225),
  foreign key(SUBJECT_ID) references SUBJECT(ID),      #外链到s_user表的u_id字段
  foreign key(VOUCHER_ID) references VOUCHER(ID)      #外链到s_user表的u_id字段
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;

## 凭证单号
CREATE TABLE IF NOT EXISTS ORDERNUM (
  ID         BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CURTAINID  BIGINT(20)  NOT NULL,
  MONTH      VARCHAR(20)  NOT NULL,
  NUM        BIGINT(20)  NOT NULL
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;

## 公共接口客户端信息
CREATE TABLE IF NOT EXISTS APPCLIENT (
  ID         BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  APPID      VARCHAR(20)  NOT NULL,
  SECRETKEY  VARCHAR(225)  NOT NULL
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 帐套余额
CREATE TABLE IF NOT EXISTS CURTAINBALANCE (
  ID          BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  MONTH       VARCHAR(10) NOT NULL,
  CURTAINID   BIGINT(20) NOT NULL,
  SUBJECTID  BIGINT(20) NOT NULL,
  DEBIT       DOUBLE,
  CREDIT      DOUBLE,
  DEBITAT     DOUBLE,
  CREDITAT    DOUBLE,
  STATUS VARCHAR(2)
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 资产负债表元素配置
CREATE TABLE IF NOT EXISTS REPORTBELEMENT (
  ID     BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  COMFLAG  VARCHAR(20) NOT NULL,
  CODE   VARCHAR(10) NOT NULL,
  NAME   VARCHAR(50),
  ROW    INT(20),
  TYPE   VARCHAR(2),
  CALFUN  VARCHAR(50)
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 资产负债表元素 与 科目 对应关系
CREATE TABLE IF NOT EXISTS REPORTB_SUBJECT (
  REPORTB_ID BIGINT(20) NOT NULL,
  CODE       VARCHAR(10)  NOT NULL,
  KEY FK_REPORTB_ID (REPORTB_ID),
  CONSTRAINT FK_REPORTB_ID FOREIGN KEY (REPORTB_ID) REFERENCES REPORTBELEMENT(ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

## 利润表元素配置
CREATE TABLE IF NOT EXISTS REPORTPELEMENT (
  ID     BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  COMFLAG  VARCHAR(20) NOT NULL,
  CODE   VARCHAR(10) NOT NULL,
  NAME   VARCHAR(50),
  ROW    INT(20),
  TYPE   VARCHAR(2)
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;
## 利润表元素 与 科目 对应关系
CREATE TABLE IF NOT EXISTS REPORTP_SUBJECT (
  REPORTP_ID BIGINT(20) NOT NULL,
  CODE       VARCHAR(10)  NOT NULL,
  KEY FK_REPORTP_ID (REPORTP_ID),
  CONSTRAINT FK_REPORTP_ID FOREIGN KEY (REPORTP_ID) REFERENCES REPORTPELEMENT(ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

## 资产负债表
CREATE TABLE IF NOT EXISTS REPORTB (
  ID     BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CURTAINID  VARCHAR(20) NOT NULL,
  MONTH   VARCHAR(10) NOT NULL,
  REPORTBELEMENTID   VARCHAR(20) NOT NULL,
  INITNUM    DOUBLE,
  LASTNUM   DOUBLE
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;

## 利润表
CREATE TABLE IF NOT EXISTS REPORTP (
  ID     BIGINT(20)   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CURTAINID  VARCHAR(20) NOT NULL,
  MONTH   VARCHAR(10) NOT NULL,
  REPORTPELEMENTID   VARCHAR(20) NOT NULL,
  MONTHNUM    DOUBLE,
  YEARNUM   DOUBLE
)
  ENGINE = MyISAM
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8;